apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-echo702e2214-07d1-42a5-b22d-ca15ef4f0e68.fullname" . }}-config
  labels:
    {{- include "go-echo702e2214-07d1-42a5-b22d-ca15ef4f0e68.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $value := .Values.envVars }}
  {{ $key }}: {{ $value }}
{{- end }}
