apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-echo55010179-7bfc-4fa2-a1a2-6288f1b416ec.fullname" . }}-config
  labels:
    {{- include "go-echo55010179-7bfc-4fa2-a1a2-6288f1b416ec.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $value := .Values.envVars }}
  {{ $key }}: {{ $value }}
{{- end }}
