apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-echob19b2812-e0cb-442d-b500-8af46511ca28.fullname" . }}-config
  labels:
    {{- include "go-echob19b2812-e0cb-442d-b500-8af46511ca28.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $value := .Values.envVars }}
  {{ $key }}: {{ $value }}
{{- end }}
