apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-echob1cbfeef-5ab9-43fa-a1bc-984162b9ca28.fullname" . }}
  labels:
    {{- include "go-echob1cbfeef-5ab9-43fa-a1bc-984162b9ca28.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: svchttp
  selector:
    {{- include "go-echob1cbfeef-5ab9-43fa-a1bc-984162b9ca28.selectorLabels" . | nindent 6 }}
