apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-echo02303969-9486-425d-aac0-94977d0b2ceb.fullname" . }}
  labels:
    {{- include "go-echo02303969-9486-425d-aac0-94977d0b2ceb.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: svchttp
  selector:
    {{- include "go-echo02303969-9486-425d-aac0-94977d0b2ceb.selectorLabels" . | nindent 6 }}
